In [1]:
import numpy as np
import tensorflow as tf
sess =tf.Session()

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
LSTM_CELL_SIZE = 4
lstm_cell = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)
state = (tf.zeros([2,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor 'zeros:0' shape=(2, 4) dtype=float32>,
 <tf.Tensor 'zeros:0' shape=(2, 4) dtype=float32>)

In [3]:
sample_input = tf.constant([[1,2,3,4,3,2],[3,2,2,2,2,2]],dtype=tf.float32)
print (sess.run(sample_input))

[[1. 2. 3. 4. 3. 2.]
 [3. 2. 2. 2. 2. 2.]]


In [4]:
with tf.variable_scope("LSTM_sample_one"):
    output, state_new = lstm_cell(sample_input, state)
sess.run(tf.global_variables_initializer())
print(sess.run(state_new))

LSTMStateTuple(c=array([[ 0.8919289 ,  0.04903587,  0.77431965, -0.02519612],
       [ 0.8661392 ,  0.01214866,  0.8003925 , -0.03606117]],
      dtype=float32), h=array([[ 0.02464016,  0.00510992,  0.06735586, -0.00364171],
       [ 0.05173204,  0.00262724,  0.05939908, -0.01440294]],
      dtype=float32))


In [5]:
print(sess.run(output))

[[ 0.02464016  0.00510992  0.06735586 -0.00364171]
 [ 0.05173204  0.00262724  0.05939908 -0.01440294]]


In [6]:
sess.close()#part one completed